### ISSUE TITLE
not send data when websocket is not open

### ISSUE THREAD

**Issue by js2me** [js2me/flamebird#11]
```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (D:\projects\flamebird\node_modules\ws\lib\websocket.js:314:19)
    at Function.send (D:\projects\flamebird\lib\ws.js:23:6)
    at Object.saveCommandData (D:\projects\flamebird\lib\processWorker.js:21:8)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onread (net.js:581:20)
```

**Comment by js2me** [comment]
https://github.com/js2me/flamebird/pull/12
