### ISSUE TITLE
fb web: UnhandledPromiseRejectionWarning: Error: spawn chrome ENOENT

### ISSUE THREAD

**Issue by js2me** [js2me/flamebird#2]
When we start `web` application. fb takes error
```
js2me@js2me-pc ~/Projects/**** $ fb web
Server started on port 5050
(node:3390) UnhandledPromiseRejectionWarning: Error: spawn chrome ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
(node:3390) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3390) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Linux, MintOS

**Comment by js2me** [comment]
for `win32` needs to use `chrome` and for `linux` needs to use `google-chrome`

**Comment by js2me** [comment]
r. 1.6.7. tested and working
